import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
// import "./globals.css";
import Header from "@/app/[locale]/Header/Header";
import Footer from "@/components/Footer";
import { Mulish } from "next/font/google";

// import "@/scss/globals.css";
import "@/scss/index.scss";

const inter = Inter({ subsets: ["latin"] });
const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ГО",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}
export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body className={mulish.className}>
        <div>
          <Header />
          <div>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
